/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LangSectionRouteImport } from './routes/$lang.$section'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangSearchRouteImport } from './routes/$lang.search'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelStoryIdRouteImport } from './routes/panel.$storyId'
import { Route as ReadStoryIdRouteImport } from './routes/read.$storyId'
import { Route as LangReadStoryIdRouteImport } from './routes/$lang.read.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSectionRoute = LangSectionRouteImport.update({
  id: '/$lang/$section',
  path: '/$lang/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/$lang/search',
  path: '/$lang/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelStoryIdRoute = PanelStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => PanelRoute,
} as any)
const ReadStoryIdRoute = ReadStoryIdRouteImport.update({
  id: '/read/$storyId',
  path: '/read/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangReadStoryIdRoute = LangReadStoryIdRouteImport.update({
  id: '/$lang/read/$storyId',
  path: '/$lang/read/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/panel': typeof PanelRouteWithChildren
  '/search': typeof SearchRoute
  '/$lang/$section': typeof LangSectionRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/search': typeof LangSearchRoute
  '/panel/$storyId': typeof PanelStoryIdRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/panel/': typeof PanelIndexRoute
  '/$lang/read/$storyId': typeof LangReadStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/$lang/$section': typeof LangSectionRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/search': typeof LangSearchRoute
  '/panel/$storyId': typeof PanelStoryIdRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/panel': typeof PanelIndexRoute
  '/$lang/read/$storyId': typeof LangReadStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/panel': typeof PanelRouteWithChildren
  '/search': typeof SearchRoute
  '/$lang/$section': typeof LangSectionRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/search': typeof LangSearchRoute
  '/panel/$storyId': typeof PanelStoryIdRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/panel/': typeof PanelIndexRoute
  '/$lang/read/$storyId': typeof LangReadStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/about'
    | '/panel'
    | '/search'
    | '/$lang/$section'
    | '/$lang/about'
    | '/$lang/search'
    | '/panel/$storyId'
    | '/read/$storyId'
    | '/panel/'
    | '/$lang/read/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/about'
    | '/search'
    | '/$lang/$section'
    | '/$lang/about'
    | '/$lang/search'
    | '/panel/$storyId'
    | '/read/$storyId'
    | '/panel'
    | '/$lang/read/$storyId'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/about'
    | '/panel'
    | '/search'
    | '/$lang/$section'
    | '/$lang/about'
    | '/$lang/search'
    | '/panel/$storyId'
    | '/read/$storyId'
    | '/panel/'
    | '/$lang/read/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  AboutRoute: typeof AboutRoute
  PanelRoute: typeof PanelRouteWithChildren
  SearchRoute: typeof SearchRoute
  LangSectionRoute: typeof LangSectionRoute
  LangAboutRoute: typeof LangAboutRoute
  LangSearchRoute: typeof LangSearchRoute
  ReadStoryIdRoute: typeof ReadStoryIdRoute
  LangReadStoryIdRoute: typeof LangReadStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$section': {
      id: '/$lang/$section'
      path: '/$lang/$section'
      fullPath: '/$lang/$section'
      preLoaderRoute: typeof LangSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/$lang/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/$storyId': {
      id: '/panel/$storyId'
      path: '/$storyId'
      fullPath: '/panel/$storyId'
      preLoaderRoute: typeof PanelStoryIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/read/$storyId': {
      id: '/read/$storyId'
      path: '/read/$storyId'
      fullPath: '/read/$storyId'
      preLoaderRoute: typeof ReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/read/$storyId': {
      id: '/$lang/read/$storyId'
      path: '/$lang/read/$storyId'
      fullPath: '/$lang/read/$storyId'
      preLoaderRoute: typeof LangReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelRouteChildren {
  PanelStoryIdRoute: typeof PanelStoryIdRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelStoryIdRoute: PanelStoryIdRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  AboutRoute: AboutRoute,
  PanelRoute: PanelRouteWithChildren,
  SearchRoute: SearchRoute,
  LangSectionRoute: LangSectionRoute,
  LangAboutRoute: LangAboutRoute,
  LangSearchRoute: LangSearchRoute,
  ReadStoryIdRoute: ReadStoryIdRoute,
  LangReadStoryIdRoute: LangReadStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
