/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LangSectionRouteImport } from './routes/$lang.$section'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangAccountRouteImport } from './routes/$lang.account'
import { Route as LangMembershipRouteImport } from './routes/$lang.membership'
import { Route as LangNewsletterRouteImport } from './routes/$lang.newsletter'
import { Route as LangPaymentRouteImport } from './routes/$lang.payment'
import { Route as LangSearchRouteImport } from './routes/$lang.search'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelStoryIdRouteImport } from './routes/panel.$storyId'
import { Route as ReadStoryIdRouteImport } from './routes/read.$storyId'
import { Route as LangReadStoryIdRouteImport } from './routes/$lang.read.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSectionRoute = LangSectionRouteImport.update({
  id: '/$lang/$section',
  path: '/$lang/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAccountRoute = LangAccountRouteImport.update({
  id: '/$lang/account',
  path: '/$lang/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LangMembershipRoute = LangMembershipRouteImport.update({
  id: '/$lang/membership',
  path: '/$lang/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LangNewsletterRoute = LangNewsletterRouteImport.update({
  id: '/$lang/newsletter',
  path: '/$lang/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPaymentRoute = LangPaymentRouteImport.update({
  id: '/$lang/payment',
  path: '/$lang/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/$lang/search',
  path: '/$lang/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelStoryIdRoute = PanelStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => PanelRoute,
} as any)
const ReadStoryIdRoute = ReadStoryIdRouteImport.update({
  id: '/read/$storyId',
  path: '/read/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangReadStoryIdRoute = LangReadStoryIdRouteImport.update({
  id: '/$lang/read/$storyId',
  path: '/$lang/read/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/editor': typeof EditorRoute
  '/membership': typeof MembershipRoute
  '/newsletter': typeof NewsletterRoute
  '/panel': typeof PanelRouteWithChildren
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/$lang/$section': typeof LangSectionRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/account': typeof LangAccountRoute
  '/$lang/membership': typeof LangMembershipRoute
  '/$lang/newsletter': typeof LangNewsletterRoute
  '/$lang/payment': typeof LangPaymentRoute
  '/$lang/search': typeof LangSearchRoute
  '/panel/$storyId': typeof PanelStoryIdRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/panel/': typeof PanelIndexRoute
  '/$lang/read/$storyId': typeof LangReadStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/editor': typeof EditorRoute
  '/membership': typeof MembershipRoute
  '/newsletter': typeof NewsletterRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/$lang/$section': typeof LangSectionRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/account': typeof LangAccountRoute
  '/$lang/membership': typeof LangMembershipRoute
  '/$lang/newsletter': typeof LangNewsletterRoute
  '/$lang/payment': typeof LangPaymentRoute
  '/$lang/search': typeof LangSearchRoute
  '/panel/$storyId': typeof PanelStoryIdRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/panel': typeof PanelIndexRoute
  '/$lang/read/$storyId': typeof LangReadStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/editor': typeof EditorRoute
  '/membership': typeof MembershipRoute
  '/newsletter': typeof NewsletterRoute
  '/panel': typeof PanelRouteWithChildren
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/$lang/$section': typeof LangSectionRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/account': typeof LangAccountRoute
  '/$lang/membership': typeof LangMembershipRoute
  '/$lang/newsletter': typeof LangNewsletterRoute
  '/$lang/payment': typeof LangPaymentRoute
  '/$lang/search': typeof LangSearchRoute
  '/panel/$storyId': typeof PanelStoryIdRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/panel/': typeof PanelIndexRoute
  '/$lang/read/$storyId': typeof LangReadStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/about'
    | '/account'
    | '/editor'
    | '/membership'
    | '/newsletter'
    | '/panel'
    | '/payment'
    | '/search'
    | '/$lang/$section'
    | '/$lang/about'
    | '/$lang/account'
    | '/$lang/membership'
    | '/$lang/newsletter'
    | '/$lang/payment'
    | '/$lang/search'
    | '/panel/$storyId'
    | '/read/$storyId'
    | '/panel/'
    | '/$lang/read/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/about'
    | '/account'
    | '/editor'
    | '/membership'
    | '/newsletter'
    | '/payment'
    | '/search'
    | '/$lang/$section'
    | '/$lang/about'
    | '/$lang/account'
    | '/$lang/membership'
    | '/$lang/newsletter'
    | '/$lang/payment'
    | '/$lang/search'
    | '/panel/$storyId'
    | '/read/$storyId'
    | '/panel'
    | '/$lang/read/$storyId'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/about'
    | '/account'
    | '/editor'
    | '/membership'
    | '/newsletter'
    | '/panel'
    | '/payment'
    | '/search'
    | '/$lang/$section'
    | '/$lang/about'
    | '/$lang/account'
    | '/$lang/membership'
    | '/$lang/newsletter'
    | '/$lang/payment'
    | '/$lang/search'
    | '/panel/$storyId'
    | '/read/$storyId'
    | '/panel/'
    | '/$lang/read/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  EditorRoute: typeof EditorRoute
  MembershipRoute: typeof MembershipRoute
  NewsletterRoute: typeof NewsletterRoute
  PanelRoute: typeof PanelRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  SearchRoute: typeof SearchRoute
  LangSectionRoute: typeof LangSectionRoute
  LangAboutRoute: typeof LangAboutRoute
  LangAccountRoute: typeof LangAccountRoute
  LangMembershipRoute: typeof LangMembershipRoute
  LangNewsletterRoute: typeof LangNewsletterRoute
  LangPaymentRoute: typeof LangPaymentRoute
  LangSearchRoute: typeof LangSearchRoute
  ReadStoryIdRoute: typeof ReadStoryIdRoute
  LangReadStoryIdRoute: typeof LangReadStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$section': {
      id: '/$lang/$section'
      path: '/$lang/$section'
      fullPath: '/$lang/$section'
      preLoaderRoute: typeof LangSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/account': {
      id: '/$lang/account'
      path: '/$lang/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/membership': {
      id: '/$lang/membership'
      path: '/$lang/membership'
      fullPath: '/$lang/membership'
      preLoaderRoute: typeof LangMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/newsletter': {
      id: '/$lang/newsletter'
      path: '/$lang/newsletter'
      fullPath: '/$lang/newsletter'
      preLoaderRoute: typeof LangNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/payment': {
      id: '/$lang/payment'
      path: '/$lang/payment'
      fullPath: '/$lang/payment'
      preLoaderRoute: typeof LangPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/$lang/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/$storyId': {
      id: '/panel/$storyId'
      path: '/$storyId'
      fullPath: '/panel/$storyId'
      preLoaderRoute: typeof PanelStoryIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/read/$storyId': {
      id: '/read/$storyId'
      path: '/read/$storyId'
      fullPath: '/read/$storyId'
      preLoaderRoute: typeof ReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/read/$storyId': {
      id: '/$lang/read/$storyId'
      path: '/$lang/read/$storyId'
      fullPath: '/$lang/read/$storyId'
      preLoaderRoute: typeof LangReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelRouteChildren {
  PanelStoryIdRoute: typeof PanelStoryIdRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelStoryIdRoute: PanelStoryIdRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  EditorRoute: EditorRoute,
  MembershipRoute: MembershipRoute,
  NewsletterRoute: NewsletterRoute,
  PanelRoute: PanelRouteWithChildren,
  PaymentRoute: PaymentRoute,
  SearchRoute: SearchRoute,
  LangSectionRoute: LangSectionRoute,
  LangAboutRoute: LangAboutRoute,
  LangAccountRoute: LangAccountRoute,
  LangMembershipRoute: LangMembershipRoute,
  LangNewsletterRoute: LangNewsletterRoute,
  LangPaymentRoute: LangPaymentRoute,
  LangSearchRoute: LangSearchRoute,
  ReadStoryIdRoute: ReadStoryIdRoute,
  LangReadStoryIdRoute: LangReadStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
